source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
inhibit_all_warnings!

use_frameworks!

target 'Granola' do
    pod 'Granola', :path => '../'
    
    pod 'Specta', '~> 1.0'
    pod 'Expecta', '~> 1.0'
    pod 'VVJSONSchemaValidation', '~> 1.3'
end
